- name: loops
  hosts: localhost
  connection: local
  tasks:
    - name: loop with list
      ansible.builtin.debug:
        msg: "The number is {{ item }}"
        loop: 
          - 1
          - 2
          - 3
          - 4
          - 5